version: '3.7'

services:
  db:
    container_name: aecr_postgres
    image: postgres:14.1
    restart: always
    environment: 
      - POSTGRES_DB=aecrdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD
  kiarapi:
    container_name: kiarapi
    image: ${DOCKER_REGISTRY-}kiarapi
    environment:
      - CUSTOMCONNSTR_postgres=host=db;port=5432;Database=aecrdb;User ID=postgres;Password=${POSTGRES_PASSWORD};
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    build:
      context: .
      dockerfile: KiarApi/Dockerfile
    depends_on:
      - "db"
    restart: on-failure

secrets:
  postgres_db_password:
    file: ./secrets/postgres_pw.txt